title: Hello, visitor! I'm Sean Lin.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ":title/"
baseurl: "/SeanWeb" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sean Lin # add your name
author-img: sean-lin.jpg # add your photo
about-author: (Updated July 2022) A Data Science graduate student a year ago. Currently a machine learning software engineer. <br/><br/>Recently focusing on building/deploying machine learning/deep learning products at scale. Always stay hungry to learn. <br/><br/>"There is no free lunch." # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: fingeronfire0704 # add your Github handle
social-linkedin: hsuan-yu-sean-lin-672667149 # add your Linkedin handle
social-email: hlin59@usfca.edu # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: UA-207440301-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
